Update github_actions_emo.yml

diff --git a/.github/workflows/github_actions_emo.yml b/.github/workflows/github_actions_emo.yml
--- a/.github/workflows/github_actions_emo.yml
+++ b/.github/workflows/github_actions_emo.yml
@@ -11,22 +11,21 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
+         env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Fetch PR details
         id: fetch_pr
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           # Use GitHub CLI to get PR details
           pr_title=$(gh pr view ${{ github.event.pull_request.number }} --json title -q ".title")
           pr_body=$(gh pr view ${{ github.event.pull_request.number }} --json body -q ".body")
+          commit_count=$(( ${{ github.event.pull_request.commits }} + 1 ))
           echo "PR_TITLE=${pr_title}" >> $GITHUB_ENV
           echo "PR_BODY=${pr_body}" >> $GITHUB_ENV
+          echo "COMMIT_COUNT=${commit_count}" >> $GITHUB_ENV
 
       - name: Validate PR Title
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo "Validating PR Title: $PR_TITLE"
           if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test): ]]; then
@@ -34,12 +33,24 @@ jobs:
             exit 1
           fi
 
+          if [[ -z "$PR_TITLE" ]]; then
+            echo "Error: PR Title is missing."
+            exit 1
+          fi
+
       - name: Validate PR Description
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           echo "Validating PR Description."
           if [[ -z "$PR_BODY" ]]; then
             echo "Error: PR description is missing."
             exit 1
           fi
+
+      - name: Validating the Commit Count
+        run: |
+          echo "Validating the Commit Count"
+          if [$COMMIT_COUNT -gt 2]; then
+            echo "There are too many commits in the PR. Keep the commit count less than 3"
+            exit 1
+          fi
+          
